### ISSUE TITLE
lien state - transition mauvaise cardinalite ?

### ISSUE THREAD

**Issue by pascalpoizat** [mosser/ArduinoML-kernel#1]
Le lien entre state et transition ne devrait il pas etre state 1--\* transition ?

**Comment by mosser** [comment]
Non, j'ai fait simple, tu ne va que dans un état (ça simplifie beaucoup la génération de code). Le but est de faire un zoo de différentes version du DSL (de A à Z), et pour l'atteindre j'ai simplifié un peu le domaine par rapport à ce que je montrais à l'EJCP. 

http://www.i3s.unice.fr/~mosser/_media/teaching/jdev15/lab_jdev.pdf

**Comment by pascalpoizat** [comment]
oui mais un état peut bien avoir plus d'une transition sortante ?
je vais re regarder
